version: '3'
services:
  # db:
  #   image: mcr.microsoft.com/mssql/server
  #   volumes:
  #     - data:/var/opt/mssql
  #   restart: always
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=${DB_PASSWORD:-SimplePassword123}
  #   ports:
  #     - 14331:1433
  try-dotnet:
    image: dev-dotnet
    build:
      cache_from:
        - dev-dotnet
      context: ../dev-dotnet
    environment:
      - PROJECT_PATH=try-dotnet
      - INIT_FILE=init.sh
      - WAIT_SEC=2
      - TZ=
    volumes:
      - type: bind
        source: ${GIT_CONFIG_PATH:-~/.gitconfig}
        target: /home/user/.gitconfig
        read_only: true
      - type: bind
        source: ${SSH_PATH:-~/.ssh}
        target: /home/user/.ssh
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /home/user/.bash_aliases
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /root/.bash_aliases
        read_only: true
      - home:/home/user:delegated
      - ../..:/opt/workspace/try-dotnet
volumes:
  data:
  home:
